/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkbenchIndexImport } from './routes/workbench/index'
import { Route as ChatsChatIdImport } from './routes/chats/$chatId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WorkbenchIndexRoute = WorkbenchIndexImport.update({
  id: '/workbench/',
  path: '/workbench/',
  getParentRoute: () => rootRoute,
} as any)

const ChatsChatIdRoute = ChatsChatIdImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/chats/$chatId': {
      id: '/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof ChatsChatIdImport
      parentRoute: typeof rootRoute
    }
    '/workbench/': {
      id: '/workbench/'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/workbench': typeof WorkbenchIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/workbench': typeof WorkbenchIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/workbench/': typeof WorkbenchIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats/$chatId' | '/workbench'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats/$chatId' | '/workbench'
  id: '__root__' | '/' | '/chats/$chatId' | '/workbench/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ChatsChatIdRoute: typeof ChatsChatIdRoute
  WorkbenchIndexRoute: typeof WorkbenchIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ChatsChatIdRoute: ChatsChatIdRoute,
  WorkbenchIndexRoute: WorkbenchIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chats/$chatId",
        "/workbench/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/chats/$chatId": {
      "filePath": "chats/$chatId.tsx"
    },
    "/workbench/": {
      "filePath": "workbench/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
